oscar_blogs/blogs/dashboard_blog/urls.py
from django.urls import path

from . import views

app_name = 'dashboard_blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='post-list'),
    path('post/create', views.PostCreateView.as_view(), name='post-create'),
    path('post/<str:slug>/update', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<str:slug>/delete', views.PostDeleteView.as_view(), name='post-delete'),

    path('category/', views.CategoryListView.as_view(), name='category-list'),
    path('category/create', views.CategoryCreateView.as_view(), name='category-create'),
    path('category/<str:slug>/update', views.CategoryUpdateView.as_view(), name='category-update'),
    path('category/<str:slug>/delete', views.CategoryDeleteView.as_view(), name='category-delete'),
]

oscar_blogs/blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.PostListView.as_view(), name='blogs-view'),
    path('category/<str:slug>', views.PostCategoryListView.as_view(), name='blogs-category-view'),
    path('post/<str:slug>/', views.PostDetailView.as_view(), name='post-detail'),
]

oscar_blogs/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include(apps.get_app_config('oscar').urls[0])),
    path('blogs/',
         include(('oscar_blogs.blogs.urls', 'blogs'),
                 namespace='blogs')),
    path('dashboard/blogs/',
         include(('oscar_blogs.blogs.dashboard_blog.urls', 'dashboard_blog'),
                 namespace='dashboard_blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oscar_blogs/blogs/models.py
from oscar.models.fields import AutoSlugField

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = AutoSlugField(populate_from="name", editable=True, max_length=255, unique=True, blank=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    excerpt = models.TextField(max_length=10000, blank=True)
    content = models.TextField(max_length=50000, blank=True)
    featured_image = models.ImageField(upload_to='image', blank=True)
    date_created = models.DateTimeField(auto_now_add=True, db_index=True)
    date_updated = models.DateTimeField(auto_now=True, db_index=True)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        null=True,
        limit_choices_to={'is_staff': True}
    )
    categories = models.ManyToManyField(Category, blank=True)
    slug = AutoSlugField(populate_from="title", editable=True, max_length=255, unique=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogs:post-detail', args=[str(self.slug)])

oscar_blogs/blogs/dashboard_blog/forms.py
from django import forms

from ..models import Category, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'slug',
            'excerpt',
            'content',
            'featured_image',
            'categories',
            'author'
        ]


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'slug']

oscar_blogs/blogs/dashboard_blog/views.py
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin, SingleTableView

from django.urls import reverse_lazy
from django.views import generic

from .filters import PostFilter
from .forms import CategoryForm, PostForm
from .tables import CategoryTable, PostTable
from ..models import Category, Post


class CategoryListView(SingleTableView):
    template_name = 'dashboard/category-list.html'
    model = Category
    table_class = CategoryTable
    context_table_name = 'category_table'


class CategoryCreateView(generic.CreateView):
    form_class = CategoryForm
    template_name = 'dashboard/category-form.html'
    success_url = reverse_lazy('dashboard_blog:category-list')
    extra_context = {'title': 'New Category', 'header': 'Add a new Category'}


class CategoryUpdateView(generic.UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'dashboard/category-form.html'
    success_url = reverse_lazy('dashboard_blog:category-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['header'] = f'Edit Category "{self.object.name}"'
        return context


class CategoryDeleteView(generic.DeleteView):
    model = Category
    template_name = 'dashboard/category-delete.html'
    success_url = reverse_lazy('dashboard_blog:category-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['header'] = f'Delete Category "{self.object.name}"'
        return context


class PostListView(SingleTableMixin, FilterView):
    template_name = 'dashboard/post-list.html'
    table_class = PostTable
    context_table_name = 'posts_table'
    model = Post
    filterset_class = PostFilter


class PostCreateView(generic.CreateView):
    form_class = PostForm
    template_name = 'dashboard/post-form.html'
    success_url = reverse_lazy('dashboard_blog:post-list')
    extra_context = {'title': 'New Post', 'header': 'Add a new Post'}


class PostUpdateView(generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'dashboard/post-form.html'
    success_url = reverse_lazy('dashboard_blog:post-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['header'] = f'Edit Post "{self.object.title}"'
        return context


class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'dashboard/post-delete.html'
    success_url = reverse_lazy('dashboard_blog:post-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['header'] = f'Delete Post "{self.object.title}"'
        return context

oscar_blogs/blogs/views.py
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin

from django.shortcuts import get_object_or_404
from django.views import generic

from .filters import PostFilter
from .models import Category, Post


class PostListView(SingleTableMixin, FilterView):
    model = Post
    template_name = 'blogs/post-list.html'
    extra_context = {'title': 'Posts', 'header': 'Recent Posts', 'categories': Category.objects.all()}
    context_object_name = 'posts'
    filterset_class = PostFilter
    ordering = ['-date_created']


class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'blogs/post-detail.html'


class PostCategoryListView(PostListView):
    extra_context = {'title': 'Posts', 'header': 'Category', 'categories': Category.objects.all()}

    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs['slug'])
        return self.category.post_set.all()

oscar_blogs/blogs/templates/blogs/post-detail.html
{% extends "oscar/layout.html" %}

{% load i18n %}
{% load image_tags %}

{% block title %}
    Blog | {{ post.title }}
{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'blogs:blogs-view' %}">
                    Blog
                </a>
            </li>
            <li class="breadcrumb-item">Post Detail</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block header %}
    <h1>{{ post.title }}</h1>
{% endblock header %}

{% block content %}
    <section id="blog-section" class="container-fluid">
        <main>
            {% if post.featured_image %}
                <div style="display: flex; justify-content: center;">
                    <img src="{% oscar_thumbnail post.featured_image '800x500' upscale=False %}" /> 
                </div>
            {% endif %}
            <h3> Content : </h3>
            {% if not post.content and not post.excerpt %}
                <p> - </p>
            {% else %}
                {% if post.content %}
                    <p style="word-wrap: break-word;">{{ post.content|safe }}</p>
                {% else %}
                    <p style="word-wrap: break-word;">{{ post.excerpt|safe }}</p>
                {% endif %}
            {% endif %}
            <hr>
            <p>Category : 
                {% for category in post.categories.all %}
                <a href="{% url 'blogs:blogs-category-view' category.slug %}">
                    {{ category.name }}
                </a>
                {% empty %}
                    Uncategorized
                {% endfor %}
            </p>
            <p>
                Post Date : {{ post.date_created|date:"d/m/Y" }}
            </p>
            <p>
                Update Date : {{ post.date_updated|date:"d/m/Y" }}
            </p>
            <p>
                Author : {{ post.author }}
            </p>
        </main>
    </section>

{% endblock content %}

oscar_blogs/blogs/templates/blogs/post-list.html
{% extends "oscar/layout.html" %}

{% load i18n %}
{% load image_tags %}

{% block title %}
    Blog | {{ title }}
{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'blogs:blogs-view' %}">Blog</a>
            </li>
            <li class="breadcrumb-item active">{{ title }}</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block header %}
    <h1>{{ header }}</h1>
{% endblock header %}

{% block content %}
    <section id="blog-section" class="container-fluid">
        <div class="row">
            
            <div class="col-md-9 pt-3" style="display: flex; justify-content: center; flex-direction: column;">
                {% if posts.exists %}
                    {% for post in posts %}
                        <article class="container-fluid card mb-4 pt-3 pb-3">
                            <div class="row">
                                <h2 style="width: 90%; margin-left: 5%; word-wrap: break-word;">
                                    <a href="{{ post.get_absolute_url }}" >
                                        {{ post.title }}
                                    </a>
                                </h2>
                            </div>
                            <div class="row">
                                <div style="width: 90%; margin-left: 5%;">
                                    {% for category in post.categories.all %}
                                        <a href="{% url 'blogs:blogs-category-view' category.slug %}">
                                            <span class="badge badge-secondary">{{ category.name }}</span>
                                        </a>   
                                    {% empty %}
                                        Uncategorized
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div style="width: 100%;">
                                    {% if post.featured_image %}
                                        <div style="width: 100%; display: flex; justify-content: center;">
                                            <img src="{% oscar_thumbnail post.featured_image '400x250' upscale=True %}" /> 
                                        </div>
                                    {% endif %}
                                        <p style="text-align: center;"><small> Post Date: {{ post.date_created|date:"d-m-Y" }} | Post By: {{ post.author }} </small></p>
                                    {% if post.excerpt%}
                                        <p style="width: 90%; margin-left: 5%; word-wrap: break-word;">
                                            {{ post.excerpt|truncatechars:500|safe}}
                                        </p>
                                    {% else %}
                                        <p style="width: 90%; margin-left: 5%; word-wrap: break-word;">
                                            {{ post.content|truncatechars:500|safe}}
                                        </p>
                                    {% endif %}

                                    <a href="{{ post.get_absolute_url }}" class="btn btn-sm btn-outline-success" style="width: 90%; margin-left: 5%;">
                                        Read more...
                                    </a>
                                    
                                </div>
                            </div>
                        </article>
                    {% endfor %}
                    {% include "oscar/partials/pagination.html" %}
                {% else %}
                    {% if search or category %}
                        <p>Data Not Found.</p>
                    {% else %}
                        <p>No published posts.</p>
                    {% endif %}
                {% endif %}
            </div>

            <div class="col-md-3">
                <nav class="blog-nav sidebar">
                    <form method="get" class="form form-inline">
                        
                        <span class="input-group-btn">
                            {% include "oscar/dashboard/partials/form_fields_inline.html" with form=filter.form style='horizontal'%}
                            <button type="submit" class="btn btn-primary" data-loading-text="{% trans 'Searching...' %}">
                                <i class="fas fa-search"></i>
                            </button>
                        </span>
                    </form>
                    <h4 class="mt-3">Categories</h4>
                    {% if categories %}
                        <ol class="list-group">
                            <li class="list-group-item">
                                <a href="{% url 'blogs:blogs-view' %}">
                                    ALL
                                </a>
                            </li>
                            {% for category in categories %}
                                <li class="list-group-item">
                                    <a href="{% url 'blogs:blogs-category-view' category.slug %}">  {% comment %} {% url 'blogs:blogs-category-view' category.slug %} {% endcomment %}
                                        {{ category.name }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ol>
                    {% else %}
                        <p>None</p>
                    {% endif %}
                </nav>
            </div>
        </div>
    </section>
{% endblock content %}

oscar_blogs/blogs/templates/dashboard/category-actions.html
{% load django_tables2 %}
{% load i18n %}

<div class="btn-toolbar">
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% trans "Actions" %}
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'dashboard_blog:category-update' slug=record.slug %}">
                {% trans "Edit" %}
            </a>
            <a class="dropdown-item" href="{% url 'dashboard_blog:category-delete' slug=record.slug %}">
                {% trans "Delete" %}
            </a>
        </div>
    </div>
</div>

oscar_blogs/blogs/templates/dashboard/category-delete.html
{% extends "oscar/dashboard/layout.html" %}
{% load i18n %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'dashboard:index' %}">
                    {% trans "Dashboard" %}
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'dashboard_blog:category-list' %}">
                    {% trans "Category" %}
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                {{ header }}
            </li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block header %}
    <div class="page-header">
        <h1>
            {{ header }}
        </h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    <div class="table-header">
        <h2>{% trans "Delete Category" %}</h2>
    </div>
    <form method="post" class="card card-body bg-light">
        {% csrf_token %}
        {{ form }}
        {% blocktrans with name=object.title %}
            <p>Do you want to delete category <strong>{{ title }}</strong>?</p>
        {% endblocktrans %}
        <div class="form-actions">
            <button type="submit" class="btn btn-danger" data-loading-text="{% trans 'Deleting...' %}">
                {% trans "Delete" %}
            </button>
            {% trans "or" %}
            <a href="{% url 'dashboard_blog:category-list' %}" class="btn btn-outline-secondary">
                {% trans "Cancel" %}
            </a>
        </div>
    </form>
{% endblock dashboard_content %}

oscar_blogs/blogs/templates/dashboard/category-form.html
{% extends 'oscar/dashboard/layout.html' %}
{% load category_tags %}
{% load i18n %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}


{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'dashboard_blog:category-list' %}">{% trans "Category" %}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                {{ header }}
            </li>
        </ol>
    </nav>
{% endblock %}

{% block headertext %}{{ title }}{% endblock %}

{% block dashboard_content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card">
        <div class="card-header">
            <h4 class="card-header-title">
                {{ header }}
            </h4>
            <div class="col-auto">
            </div>
        </div>
        <div class="card-body">
            {% include "oscar/dashboard/partials/form_fields.html" with form=form %}
        </div>
        <div>
            <a class="btn btn-danger" href="{% url 'dashboard_blog:post-list' %}">
                {% trans "Cancel" %}
            </a>
            <button class="btn btn-primary" name="action" type="submit" value="save" data-loading-text="{% trans 'Saving...' %}">
                {% trans "Save" %}
            </button>
        </div>
    </div>
</form>
</br>
{% endblock dashboard_content %}

oscar_blogs/blogs/templates/dashboard/category-list.html
{% extends "oscar/dashboard/layout.html" %}
{% load i18n %}
{% load render_table from django_tables2 %}

{% block title %}
    {% trans "Blog Posts" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'dashboard:index' %}">
                    {% trans "Dashboard" %}
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                {% trans "Category" %}
            </li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block header %}
    <div class="page-header">
        <a class="btn btn-outline-primary float-right" href="{% url 'dashboard_blog:category-create' %}">
            <i class="fas fa-plus-circle"></i>
            {% trans "Create new category" %}
        </a>
        <h1>
            {% trans "Category" %}
        </h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    {% render_table category_table %}
{% endblock dashboard_content %}

oscar_blogs/blogs/templates/dashboard/post-actions.html
{% load django_tables2 %}
{% load i18n %}

<div class="btn-toolbar">
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% trans "Actions" %}
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'dashboard_blog:post-update' slug=record.slug %}">
                {% trans "Edit" %}
            </a>
            <a class="dropdown-item" href="{{ record.get_absolute_url }}">
                {% trans "View On Site" %}
            </a>
            <a class="dropdown-item" href="{% url 'dashboard_blog:post-delete' slug=record.slug %}">
                {% trans "Delete" %}
            </a>
        </div>
    </div>
</div>

oscar_blogs/blogs/templates/dashboard/post-create.html
{% extends "oscar/dashboard/layout.html" %}
{% load i18n %}

{% block title %}
    {% trans "Blog Posts" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'dashboard:index' %}">
                    {% trans "Dashboard" %}
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                {% trans "Blog" %}
            </li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block header %}
    <div class="page-header">
        <h1>
            {% trans "Create new post" %}
        </h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    <div class="container">
        <form action="{% url 'dashboard_blog:post-create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                {{ form.title.label_tag }}
                {{ form.title }}
            </div>
            <div>
                {{ form.slug.label_tag }}
                {{ form.slug }}
            </div>
            <div>
                {{ form.excerpt.label_tag }}
                {{ form.excerpt }}
            </div>
            <div>
                {{ form.content.label_tag }}
                {{ form.content }}
            </div>
            <div>
                {{ form.featured_image.label_tag }}
                {{ form.featured_image }}
            </div>
            <div>
                {{ form.categories.label_tag }}
                {{ form.categories }}
            </div>
            <div>
                {{ form.author.label_tag }}
                {{ form.author }}
            </div>
            <button class="btn btn-success" type="submit">Create Post</button>
            
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock dashboard_content %}

oscar_blogs/blogs/templates/dashboard/post-delete.html
{% extends "oscar/dashboard/layout.html" %}
{% load i18n %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'dashboard:index' %}">
                    {% trans "Dashboard" %}
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'dashboard_blog:post-list' %}">
                    {% trans "Posts" %}
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                {{ header }}
            </li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block header %}
    <div class="page-header">
        <h1>
            {{ header }}
        </h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    <div class="table-header">
        <h2>{% trans "Delete Post" %}</h2>
    </div>
    <form method="post" class="card card-body bg-light">
        {% csrf_token %}
        {{ form }}
        {% blocktrans with name=object.title %}
            <p>Do you want to delete post <strong>{{ title }}</strong>?</p>
        {% endblocktrans %}
        <div class="form-actions">
            <button type="submit" class="btn btn-danger" data-loading-text="{% trans 'Deleting...' %}">
                {% trans "Delete" %}
            </button>
            {% trans "or" %}
            <a href="{% url 'dashboard_blog:post-list' %}" class="btn btn-outline-secondary">
                {% trans "Cancel" %}
            </a>
        </div>
    </form>
{% endblock dashboard_content %}

oscar_blogs/blogs/templates/dashboard/post-form.html
{% extends 'oscar/dashboard/layout.html' %}
{% load category_tags %}
{% load i18n %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}


{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'dashboard_blog:post-list' %}">{% trans "Blogs" %}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                {{ header }}
            </li>
        </ol>
    </nav>
{% endblock %}

{% block headertext %}{{ title }}{% endblock %}

{% block dashboard_content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card">
        <div class="card-header">
            <h4 class="card-header-title">
                {{ header }}
            </h4>
            <div class="col-auto">
            </div>
        </div>
        <div class="card-body">
            {% include "oscar/dashboard/partials/form_fields.html" with form=form %}
        </div>
        <div>
            <a class="btn btn-danger" href="{% url 'dashboard_blog:post-list' %}">
                {% trans "Cancel" %}
            </a>
            <button class="btn btn-primary" name="action" type="submit" value="save" data-loading-text="{% trans 'Saving...' %}">
                {% trans "Save" %}
            </button>
        </div>
    </div>
</form>
</br>
{% endblock dashboard_content %}

oscar_blogs/blogs/templates/dashboard/post-list.html
{% extends "oscar/dashboard/layout.html" %}
{% load i18n %}
{% load render_table from django_tables2 %}

{% block title %}
    {% trans "Blog Posts" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'dashboard:index' %}">
                    {% trans "Dashboard" %}
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                {% trans "Blogs" %}
            </li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block header %}
    <div class="page-header">
        <a class="btn btn-outline-primary float-right" href="{% url 'dashboard_blog:post-create' %}">
            <i class="fas fa-plus-circle"></i>
            {% trans "Create new post" %}
        </a>
        <h1>
            {% trans "Posts" %}
        </h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    {% block search_posts %}
        <div class="table-header">
            <h3>
                <i class="fas fa-search"></i>
                {% trans "Search Posts" %}
            </h3>
        </div>
        <div class="card card-body">
            <form method="get" class="form form-inline">
                {% include "oscar/dashboard/partials/form_fields_inline.html" with form=filter.form style='horizontal'%}
                <button type="submit" class="btn btn-primary" data-loading-text="{% trans 'Searching...' %}">
                    <i class="fas fa-search"></i>
                    {% trans "Search" %}
                </button>
            </form>
        </div>
    {% endblock search_posts %}
    <div class="table-header">
        <h3>
            {% trans "Posts" %}
        </h3>
    </div>
    {% render_table posts_table %}
{% endblock dashboard_content %}